openapi: 3.0.3
info:
  title: Example API
  description: Title
  version: 1.0.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html 
  contact:
    name: Morten Slaatten Berg
    email: mortenberg80@gmail.com
    url: https://github.com/mortenberg80
servers:
  - url: 'http://localhost:8080'
    description: Test
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      operationId: getUsers
      responses:
        '200':
          description: A JSON array of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
      parameters:
        - schema:
            type: string
          in: header
          name: foo
          description: bar
    post:
      summary: Create a new user
      description: foo
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUserRequest'
          application/v2+json:
            schema:
              $ref: '#/components/schemas/PostUserRequestv2'
      responses:
        '201':
          description: User is successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  '/users/{id}':
    parameters:
      - name: id
        description: "id of user"
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Get user by id
      description: Gets a user by its id. Use accept header to control which response types you want to receive.
      operationId: getUserById
      responses:
        '200':
          description: Successfully retrieved user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                example-1:
                  value:
                    id: string
                    person_id: string
                    first_name: string
                    last_name: string
                    date_of_birth: '2019-08-24'
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'
            application/v2+json:
              schema:
                $ref: '#/components/schemas/Userv2'
              examples:
                example-1:
                  value:
                    id: string
                    person_id: string
                    first_name: string
                    last_name: string
                    email: foo@bar.com
                    date_of_birth: '2019-08-24'
                    created_at: '2019-08-24T14:15:22Z'
                    updated_at: '2019-08-24T14:15:22Z'                    
            application/xml:
              schema:
                $ref: '#/components/schemas/Userv2'
components:
  schemas:
    User:
      type: object
      required:
        - id
        - person_id
        - first_name
        - last_name
      properties:
        id:
          type: string
        person_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        date_of_birth:
          type: string
          format: date
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    Userv2:
      type: object
      required:
        - id
        - person_id
        - first_name
        - last_name
        - email
      properties:
        id:
          type: string
        person_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        date_of_birth:
          type: string
          format: date
        email:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    GetUsersResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
    PostUserRequest:
      type: object
      required:
        - person_id
        - first_name
        - last_name
      properties:
        person_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        date_of_birth:
          type: string
          format: date
    PostUserRequestv2:
      type: object
      required:
        - person_id
        - first_name
        - last_name
        - email
      properties:
        person_id:
          type: string
        first_name:
          type: string
        last_name:
          type: string
        date_of_birth:
          type: string
          format: date
        email:
          type: string
