openapi: 3.0.3
info:
  title: Example API
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
    description: Test

paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUsersResponse'
    post:
      summary: Create a new user
      description: foo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUserRequest'
      responses:
        201:
          description: User is successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

components:
  schemas:
    User:
      type: object
      required:
        - id
        - person_id
      properties:
        id:
          type: string
        person_id:
          type: string
    GetUsersResponse:
      type: object
      properties:
        users:
          type: array
          items:
            $ref: '#/components/schemas/User'
    PostUserRequest:
      type: object
      required:
        - person_id
      properties:
        person_id:
          type: string
